export const PlanetAssetRegistry = {
  common: [
    '/assets/planet/common/rock_largeA.glb',
    '/assets/planet/common/rock_largeB.glb',
    '/assets/planet/common/rock_largeC.glb',
    '/assets/planet/common/rock_smallA.glb',
    '/assets/planet/common/rock_smallB.glb',
    '/assets/planet/common/rock_smallC.glb',
    '/assets/planet/common/stone_largeA.glb',
    '/assets/planet/common/stone_largeB.glb',
    '/assets/planet/common/stone_smallA.glb',
    '/assets/planet/common/stone_smallB.glb',
  ],
  forest: [
    '/assets/planet/forest/tree_default.glb',
    '/assets/planet/forest/tree_oak.glb',
    '/assets/planet/forest/tree_pineTallA.glb',
    '/assets/planet/forest/tree_pineRoundC.glb',
    '/assets/planet/forest/tree_simple.glb',
    '/assets/planet/forest/plant_bushDetailed.glb',
    '/assets/planet/forest/plant_bushLarge.glb',
    '/assets/planet/forest/grass_large.glb',
    '/assets/planet/forest/grass_leafsLarge.glb',
    '/assets/planet/forest/flower_yellowA.glb',
    '/assets/planet/forest/mushroom_redGroup.glb',
    '/assets/planet/forest/stump_roundDetailed.glb',
  ],
  desert: [
    '/assets/planet/desert/cactus_short.glb',
    '/assets/planet/desert/cactus_tall.glb',
    '/assets/planet/desert/plant_flatShort.glb',
    '/assets/planet/desert/plant_flatTall.glb',
    '/assets/planet/desert/rock_tallA.glb',
    '/assets/planet/desert/rock_tallB.glb',
    '/assets/planet/desert/stone_tallA.glb',
    '/assets/planet/desert/stone_tallB.glb',
    '/assets/planet/desert/cliff_rock.glb',
    '/assets/planet/desert/cliff_large_rock.glb',
  ],
  ice: [
    '/assets/planet/ice/tree_pineDefaultA.glb',
    '/assets/planet/ice/tree_pineDefaultB.glb',
    '/assets/planet/ice/stone_tallC.glb',
    '/assets/planet/ice/stone_tallD.glb',
    '/assets/planet/ice/stone_largeC.glb',
    '/assets/planet/ice/stone_smallC.glb',
    '/assets/planet/ice/rock_smallFlatA.glb',
    '/assets/planet/ice/rock_smallFlatB.glb',
  ],
  volcanic: [
    '/assets/planet/volcanic/cliff_rock.glb',
    '/assets/planet/volcanic/cliff_large_rock.glb',
    '/assets/planet/volcanic/cliff_block_rock.glb',
    '/assets/planet/volcanic/cliff_steps_rock.glb',
    '/assets/planet/volcanic/rock_tallG.glb',
    '/assets/planet/volcanic/rock_tallH.glb',
    '/assets/planet/volcanic/rock_largeE.glb',
    '/assets/planet/volcanic/rock_smallG.glb',
    '/assets/planet/volcanic/statue_obelisk.glb',
  ],
  oceanic: [
    '/assets/planet/oceanic/lily_large.glb',
    '/assets/planet/oceanic/lily_small.glb',
    '/assets/planet/oceanic/ground_riverRocks.glb',
    '/assets/planet/oceanic/cliff_waterfall_rock.glb',
    '/assets/planet/oceanic/cliff_waterfallTop_rock.glb',
    '/assets/planet/oceanic/rock_smallFlatC.glb',
    '/assets/planet/oceanic/rock_largeD.glb',
    '/assets/planet/oceanic/canoe.glb',
  ],
  rocky: [
    '/assets/planet/rocky/stone_tallE.glb',
    '/assets/planet/rocky/stone_tallF.glb',
    '/assets/planet/rocky/stone_largeD.glb',
    '/assets/planet/rocky/stone_largeE.glb',
    '/assets/planet/rocky/stone_smallG.glb',
    '/assets/planet/rocky/stone_smallH.glb',
    '/assets/planet/rocky/rock_tallI.glb',
    '/assets/planet/rocky/rock_tallJ.glb',
    '/assets/planet/rocky/statue_columnDamaged.glb',
    '/assets/planet/rocky/statue_head.glb',
  ],
  licenses: [
    '/assets/planet/licenses/README.md',
    '/assets/planet/licenses/kenney_nature_kit_license.txt',
    '/assets/planet/licenses/kenney_nature_kit_expanded.md',
  ],
} as const;
