import * as T from 'three';
import { OrbitControls } from 'three/examples/jsm/controls/OrbitControls.js';
import { TransformControls } from 'three/examples/jsm/controls/TransformControls.js';
import { ENTITY_TYPES,FX_CATALOG,MODEL_NAMES,createEntity,randomizeEntity,removeSceneEntity,emptyScene,sceneFromWorld,readScene,validateScene,DRAFT_KEY,PROJECTS_KEY,PLAY_KEY,type SceneDocument,type EntityKind } from '../../world/generation/SceneDocument';
import { SceneComposer } from '../../world/generation/SceneComposer';
import { SURFACES,MATERIALS,CLOUDS,ATMOSPHERES,RINGS,OBJECTS,STRUCTURES,PHENOMENA } from '../../world/environments/EnvironmentLibrary';
import { REVIEW_WORLDS } from '../../world/environments/EnvironmentReviewWorlds';
import { SceneHistory } from './SceneHistory';
import { renderInspector } from './Inspector';
import './style.css';

if(new URLSearchParams(location.search).has('play')){void import('./PlayMode').then(m=>m.startPlay());}else startEditor();
function startEditor(){
  const root=document.querySelector<HTMLElement>('#environments')!;
  root.innerHTML=`<header><a href="/">UNIVERSE <b>EXPLORER</b></a><span class="workshop-title">UNIVERSE WORKSHOP</span><a href="/" target="_blank" rel="noopener">Play ↗</a></header>
  <div class="document-bar"><input id="scene-name" aria-label="Project name" maxlength="96"><span id="save-state">Local project</span><button id="undo" title="Ctrl+Z">↶ Undo</button><button id="redo" title="Ctrl+Y">↷ Redo</button><button id="save">Save project</button><button id="projects">Projects</button><button id="export">Export JSON</button><button id="import">Import</button><button id="play" class="primary">Fly in scene ↗</button></div>
  <nav class="mobile-tabs"><button data-panel="library">Objects</button><button data-panel="scene">Scene</button><button data-panel="inspector">Settings</button></nav>
  <main class="workspace" data-panel="scene"><aside class="library-panel"><section><small>CREATE</small><h2>Game library</h2><input id="search" type="search" placeholder="Find an object type…" aria-label="Search library"><div id="library"></div></section>
  <section class="world-templates"><h3>Start from a game world</h3><select id="world" aria-label="Source game world"></select><div class="button-row"><button id="load-world">Open world</button><button id="new">Empty scene</button></div></section>
  <section><div class="section-heading"><h3>Scene objects</h3><span id="object-count"></span></div><button id="environment" class="wide">Environment and lighting</button><div id="entities" role="list"></div></section></aside>
  <section class="center"><div class="viewport-toolbar"><button id="focus">Focus object</button><button id="frame-all">Whole scene</button><select id="transform" aria-label="Transform tool"><option value="translate">Move</option><option value="rotate">Rotate</option><option value="scale">Scale</option><option value="none">Hide gizmo</option></select><select id="quality" aria-label="Quality"><option>HIGH</option><option>LOW</option></select><button id="pause">Pause</button><button id="pin">Capture A</button><button id="compare" disabled>A / B</button><button id="screenshot">PNG</button></div>
  <div id="stage"><div id="reference" hidden><span>A · captured view</span><img alt="Captured scene A"></div><div id="canvas-host"></div><div class="stage-title"><small>LIVE SCENE</small><span id="selected-title"></span></div><div class="stage-hint">Orbit: drag / touch · Zoom: scroll / pinch · Select: click an object</div></div>
  <div class="selection-actions"><button id="randomize">New variant</button><button id="duplicate">Duplicate</button><button id="remove">Delete object</button><span id="metrics"></span></div><div id="status" role="status">Select an object and edit it on the right. All layers are saved together.</div>
  <details class="guide"><summary>How to use the workshop</summary><p>Add objects from the library and select them in the list or scene. The inspector contains all settings for the selected type. Rings, Moons and Clouds work together. Use the scene gizmo to move, rotate and scale, or enter precise values in the inspector.</p><p>Projects and drafts are stored in this browser. JSON transfers a complete scene to another computer. Fly in scene opens a separate local preview with ship controls. Scenes are not published to the shared universe, and game progress is unchanged.</p><p>Per scene: up to 64 objects, 6 detailed planets or separate moons, 4 Epic FX and 4 additional lights. Generated moons and up to 600 instances per field have separate controls. HIGH/LOW changes detail budgets.</p></details></section>
  <aside class="inspector-panel" id="inspector"></aside></main>
  <dialog id="project-dialog"><div class="dialog-heading"><h2>Saved projects</h2><button id="close-projects">Close</button></div><div id="project-list"></div><p class="help">Up to 12 projects in this browser. Export JSON for transfer and backup.</p></dialog>
  <input id="file" type="file" accept=".json,application/json" hidden>`;
  const $=<E extends HTMLElement>(id:string)=>document.getElementById(id) as E;
  const world=$<HTMLSelectElement>('world');for(const [i,w] of REVIEW_WORLDS.entries()){const o=document.createElement('option');o.value=String(i);o.textContent=`${w.body.name} / ${w.system.anchor.title}`;world.append(o);}
  const params=new URLSearchParams(location.search),worldIndex=Math.max(0,Math.min(31,Number(params.get('world'))||4));world.value=String(worldIndex);
  let initial=sceneFromWorld(worldIndex),restoreNotice='';
  try{const draft=localStorage.getItem(DRAFT_KEY);if(draft&&!params.has('world')){initial=readScene(draft);restoreNotice="Last draft restored.";}}catch{restoreNotice="Could not restore the draft. It remains in storage; you can export the current world separately.";}
  const history=new SceneHistory(initial);let selected=initial.entities[0]?.id??'',serial=Date.now(),paused=false,elapsed=0,last=0,raf=0,frameCount=0,sampleTime=0,comparing=false,pinned=false;
  let composer=new SceneComposer(params.get('quality')==='LOW');const quality=$<HTMLSelectElement>('quality');quality.value=composer.low?'LOW':'HIGH';
  const host=$('canvas-host'),stage=$('stage'),camera=new T.PerspectiveCamera(48,1,1,2000000),renderer=new T.WebGLRenderer({antialias:true,powerPreference:'high-performance',preserveDrawingBuffer:true});
  renderer.outputColorSpace=T.SRGBColorSpace;renderer.toneMapping=T.ACESFilmicToneMapping;host.append(renderer.domElement);renderer.domElement.setAttribute('aria-label',"Editable game scene");
  const controls=new OrbitControls(camera,renderer.domElement);controls.enableDamping=true;controls.minDistance=5;controls.maxDistance=1500000;
  const transform=new TransformControls(camera,renderer.domElement);transform.setSize(.8);composer.scene.add(transform);let transforming=false;
  transform.addEventListener('dragging-changed',event=>{transforming=!!event.value;controls.enabled=!transforming;});
  transform.addEventListener('objectChange',()=>{if(transform.getMode()==='scale'&&transform.object){const axis=transform.axis??'X',scale=axis==='Y'?transform.object.scale.y:axis==='Z'?transform.object.scale.z:transform.object.scale.x;transform.object.scale.setScalar(Math.max(.01,Math.min(100,scale)));}});
  transform.addEventListener('mouseUp',()=>{if(!selected||!transform.object)return;const obj=transform.object;commit(d=>{const e=d.entities.find(e=>e.id===selected)!;e.position=obj.position.toArray().map(round) as [number,number,number];e.rotation=[obj.rotation.x,obj.rotation.y,obj.rotation.z].map(x=>round(x*180/Math.PI)) as [number,number,number];e.scale=Math.min(100,Math.max(.01,round(obj.scale.x)));});});
  function round(n:number){return Math.round(n*1000)/1000;}
  function notice(message:string,error=false){$('status').textContent=message;$('status').classList.toggle('error',error);}
  function entity(){return history.current.entities.find(e=>e.id===selected);}
  function saveDraft(){try{localStorage.setItem(DRAFT_KEY,JSON.stringify(history.current));$('save-state').textContent="Draft saved";}catch{$('save-state').textContent="Storage unavailable — export JSON";}}
  function sync(save=true,inspector=true){composer.sync(history.current);renderer.toneMappingExposure=Number(history.current.settings.exposure);$('scene-name').setAttribute('title',history.current.name);$<HTMLInputElement>('scene-name').value=history.current.name;if(!entity())selected='';
    $('selected-title').textContent=entity()?.name??history.current.name;$<HTMLButtonElement>('undo').disabled=!history.canUndo;$<HTMLButtonElement>('redo').disabled=!history.canRedo;
    $('object-count').textContent=`${history.current.entities.length} / 64`;for(const id of ['duplicate','remove'])$<HTMLButtonElement>(id).disabled=!entity();
    renderList();if(inspector)inspect();attach();if(save)saveDraft();}
  function commit(change:(d:SceneDocument)=>void,inspector=true){const next=structuredClone(history.current);try{change(next);history.commit(next);sync(true,inspector);notice("Changes applied to the scene.");}catch(error){notice((error as Error).message,true);composer.sync(history.current);inspect();attach();}}
  function attach(){const obj=composer.object(selected);if(obj&&entity()?.visible&&$<HTMLSelectElement>('transform').value!=='none')transform.attach(obj);else transform.detach();}
  function select(id:string){selected=id;renderList();inspect();attach();$('selected-title').textContent=entity()?.name??history.current.name;for(const b of ['duplicate','remove'])$<HTMLButtonElement>(b).disabled=!entity();}
  function inspect(){renderInspector($('inspector'),history.current,entity(),(key,value)=>commit(d=>{
    const e=d.entities.find(e=>e.id===selected);if(key==='$name'){if(e)e.name=String(value);else d.name=String(value);return;}if(!e){d.settings[key]=value;return;}
    if(key==='$parent')e.parent=String(value)||null;else if(key==='$visible')e.visible=!!value;else if(key==='$scale')e.scale=Number(value);else if(key.startsWith('$position.')||key.startsWith('$rotation.')){const [prop,index]=key.slice(1).split('.');e[prop as 'position'|'rotation'][Number(index)]=Number(value);}else {e.params[key]=value;const p=e.params;
      if(key==='surface'){const s=SURFACES[Number(value)],m=MATERIALS[Number(value)*2];Object.assign(p,{texture:'',material:Number(value)*2,color0:s.colors[0],color1:s.colors[1],color2:s.colors[2],color3:s.colors[3],geography:s.geography,warp:s.warp,ocean:s.oceanLevel,relief:m.relief,roughness:m.roughness});}
      if(key==='material'){const m=MATERIALS[Number(value)];Object.assign(p,{roughness:m.roughness,relief:m.relief});}
      if(key==='clouds'&&Number(value)>=0){const c=CLOUDS[Number(value)];Object.assign(p,{cloudCoverage:c.coverage,cloudAltitude:c.altitude,cloudSpeed:c.speed});}
      if(key==='atmosphere'&&Number(value)>=0){const a=ATMOSPHERES[Number(value)];Object.assign(p,{atmosphereThickness:a.thickness,atmosphereDensity:a.density});}
      if(key==='ring'&&Number(value)>=0){const r=RINGS[Number(value)];if(e.kind==='ring')Object.assign(p,{inner:r.inner,outer:r.outer});else Object.assign(p,{ringInner:r.inner,ringOuter:r.outer});}
      if(key==='objects'){const o=OBJECTS[Number(value)];Object.assign(p,{color:'#'+o.material.toString(16).padStart(6,'0'),roughness:o.roughness,metalness:o.metalness});}
    }
  }));}
  function renderList(){const list=$('entities');list.replaceChildren();for(const e of history.current.entities){const row=document.createElement('div');row.className='entity-row';row.classList.toggle('selected',e.id===selected);row.dataset.id=e.id;row.setAttribute('role','listitem');const eye=document.createElement('button');eye.textContent=e.visible?'◉':'○';eye.title=e.visible?"Hide":"Show";eye.setAttribute('aria-label',`${eye.title}: ${e.name}`);eye.onclick=()=>commit(d=>{d.entities.find(x=>x.id===e.id)!.visible=!e.visible;});const b=document.createElement('button');b.className='entity-select';b.textContent=(e.parent?'↳ ':'')+e.name;b.title=ENTITY_TYPES[e.kind].name;b.onclick=()=>select(e.id);row.append(eye,b);list.append(row);}}
  function renderLibrary(){const target=$('library'),search=$<HTMLInputElement>('search').value.toLowerCase();target.replaceChildren();for(const [kind,entry] of Object.entries(ENTITY_TYPES)){if(search&&!entry.name.toLowerCase().includes(search))continue;const button=document.createElement('button');button.textContent=`＋ ${entry.name}`;button.dataset.kind=kind;button.onclick=()=>add(kind as EntityKind);target.append(button);}}
  function add(kind:EntityKind){const e=createEntity(kind,`object-${++serial}`),source=entity();if(source){e.position=[...source.position];const radius=Number(source.params.radius)||700;if(kind==='ring'){e.params.radius=radius;}else e.position[0]+=radius*3;}
    commit(d=>{d.entities.push(e);});if(history.current.entities.some(x=>x.id===e.id)){select(e.id);focus(e.id);document.querySelector('.workspace')!.setAttribute('data-panel','inspector');}}
  function focus(id?:string){const box=composer.bounds(id);let center=box.getCenter(new T.Vector3()),size=Math.max(150,Math.max(...box.getSize(new T.Vector3()).toArray())*.5);const e=history.current.entities.find(e=>e.id===id);if(e&&(e.kind==='planet'||e.kind==='moon')){const obj=composer.object(e.id)!;center=obj.getWorldPosition(new T.Vector3());size=Number(e.params.radius)*obj.getWorldScale(new T.Vector3()).x*Math.max(1,Number(e.params.ring)>=0?Number(e.params.ringOuter):1);}controls.target.copy(center);camera.position.copy(center).add(new T.Vector3(.42,.25,1).normalize().multiplyScalar(size*2.5));controls.update();}
  function download(data:Blob,name:string){const url=URL.createObjectURL(data),a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),30000);}
  $('search').oninput=renderLibrary;$('environment').onclick=()=>select('');$('focus').onclick=()=>focus(selected||undefined);$('frame-all').onclick=()=>focus();
  $('undo').onclick=()=>{if(history.undo()){sync();notice("Action undone.");}};$('redo').onclick=()=>{if(history.redo()){sync();notice("Action restored.");}};
  $('duplicate').onclick=()=>{const e=entity();if(!e)return;const copy=structuredClone(e);copy.id=`object-${++serial}`;copy.name=`${e.name.slice(0,85)} · copy`;copy.position[0]+=(Number(copy.params.radius)||250)*2;commit(d=>{d.entities.push(copy);});if(history.current.entities.some(x=>x.id===copy.id))select(copy.id);};
  $('randomize').onclick=()=>{if(!entity())return;commit(d=>{randomizeEntity(d.entities.find(e=>e.id===selected)!,`variant-${++serial}`);});};
  $('remove').onclick=()=>{const id=selected;commit(d=>{removeSceneEntity(d,id);});};
  $<HTMLInputElement>('scene-name').onchange=event=>commit(d=>{d.name=(event.target as HTMLInputElement).value;});
  $('load-world').onclick=()=>{const next=sceneFromWorld(Number(world.value));history.commit(next);selected=next.entities[0].id;sync();focus(selected);notice("Game world opened as an editable copy. Use Undo to restore the previous scene.");};
  $('new').onclick=()=>{history.commit(emptyScene());selected='';sync();focus();};
  $<HTMLSelectElement>('transform').onchange=()=>{const mode=$<HTMLSelectElement>('transform').value;if(mode!=='none')transform.setMode(mode as 'translate'|'rotate'|'scale');attach();};
  quality.onchange=()=>{transform.detach();transform.removeFromParent();composer.dispose();composer=new SceneComposer(quality.value==='LOW');composer.scene.add(transform);sync(false);};
  $('pause').onclick=()=>{paused=!paused;$('pause').textContent=paused?"Resume":"Pause";};
  $('pin').onclick=()=>{transform.visible=false;renderer.render(composer.scene,camera);$<HTMLImageElement>('reference').querySelector('img')!.src=renderer.domElement.toDataURL('image/png');transform.visible=true;pinned=true;$<HTMLButtonElement>('compare').disabled=false;notice("View A captured. Change the scene and enable A / B.");};
  $('compare').onclick=()=>{if(!pinned)return;comparing=!comparing;$('reference').hidden=!comparing;stage.classList.toggle('comparing',comparing);};
  $('screenshot').onclick=()=>{transform.visible=false;renderer.render(composer.scene,camera);renderer.domElement.toBlob(blob=>{if(blob)download(blob,'universe-scene.png');});transform.visible=true;};
  $('export').onclick=()=>download(new Blob([JSON.stringify(history.current,null,2)],{type:'application/json'}),'universe-scene.json');
  $('import').onclick=()=>$<HTMLInputElement>('file').click();$<HTMLInputElement>('file').onchange=async event=>{const input=event.target as HTMLInputElement,file=input.files?.[0];if(!file)return;try{if(file.size>512000)throw Error("The file exceeds 512 KB.");const next=readScene(await file.text());history.commit(next);selected=next.entities[0]?.id??'';sync();focus();notice("The full scene has been restored from JSON.");}catch(error){notice(`Import rejected: ${(error as Error).message}`,true);}input.value='';};
  function projects():SceneDocument[]{try{const list=JSON.parse(localStorage.getItem(PROJECTS_KEY)||'[]');return Array.isArray(list)?list.slice(0,12).flatMap(d=>{try{return [validateScene(d)];}catch{return [];}}):[];}catch{return [];}}
  $('save').onclick=()=>{try{const list=projects(),index=list.findIndex(p=>p.name===history.current.name);if(index>=0)list[index]=history.current;else{if(list.length>=12)throw Error("12 projects are already saved. Export or delete one first.");list.push(history.current);}localStorage.setItem(PROJECTS_KEY,JSON.stringify(list));notice(`Project “${history.current.name}” saved.`);}catch(error){notice((error as Error).message,true);}};
  function projectList(){const list=$('project-list');list.replaceChildren();for(const [i,p] of projects().entries()){const row=document.createElement('div');row.className='project-row';const name=document.createElement('span');name.textContent=`${p.name} · ${p.entities.length} objects`;const open=document.createElement('button');open.textContent="Open";open.onclick=()=>{history.commit(p);selected=p.entities[0]?.id??'';sync();focus();$<HTMLDialogElement>('project-dialog').close();};const remove=document.createElement('button');remove.textContent="Delete";remove.onclick=()=>{try{localStorage.setItem(PROJECTS_KEY,JSON.stringify(projects().filter((_,j)=>i!==j)));projectList();}catch{notice("Could not update storage.",true);}};row.append(name,open,remove);list.append(row);}if(!list.children.length)list.textContent="No saved projects yet.";}
  $('projects').onclick=()=>{projectList();$<HTMLDialogElement>('project-dialog').showModal();};$('close-projects').onclick=()=>$<HTMLDialogElement>('project-dialog').close();
  $('play').onclick=()=>{try{localStorage.setItem(PLAY_KEY,JSON.stringify(history.current));window.open(`/environments.html?play=1&quality=${quality.value}`,'_blank','noopener');notice("Local flight preview opened for this scene.");}catch{notice("Could not transfer the scene. Check browser storage access.",true);}};
  document.querySelectorAll<HTMLElement>('[data-panel]').forEach(el=>{if(el.tagName==='BUTTON')el.onclick=()=>document.querySelector('.workspace')!.setAttribute('data-panel',el.dataset.panel!);});
  window.addEventListener('keydown',event=>{if((event.target as HTMLElement).matches('input,textarea,select'))return;if((event.ctrlKey||event.metaKey)&&event.code==='KeyZ'){event.preventDefault();(event.shiftKey?$('redo'):$('undo')).click();}if((event.ctrlKey||event.metaKey)&&event.code==='KeyY'){event.preventDefault();$('redo').click();}if(event.code==='KeyF')focus(selected||undefined);if(event.code==='Delete')$('remove').click();});
  const raycaster=new T.Raycaster(),pointer=new T.Vector2();let down=[0,0];renderer.domElement.addEventListener('pointerdown',event=>{down=[event.clientX,event.clientY];});renderer.domElement.addEventListener('pointerup',event=>{if(transforming||transform.axis||Math.hypot(event.clientX-down[0],event.clientY-down[1])>4)return;const rect=renderer.domElement.getBoundingClientRect();pointer.set((event.clientX-rect.left)/rect.width*2-1,-(event.clientY-rect.top)/rect.height*2+1);raycaster.setFromCamera(pointer,camera);const hit=raycaster.intersectObjects(composer.objects.children,true).find(hit=>{let node:T.Object3D|null=hit.object;while(node&&node!==composer.objects){if(!node.visible)return false;node=node.parent;}return true;});let object:T.Object3D|null=hit?.object??null;while(object&&!object.userData.editorId)object=object.parent;if(object)select(String(object.userData.editorId));});
  const resize=new ResizeObserver(()=>{const w=host.clientWidth,h=host.clientHeight;if(!w||!h)return;renderer.setPixelRatio(Math.min(devicePixelRatio,composer.low?1:1.5));renderer.setSize(w,h);camera.aspect=w/h;camera.updateProjectionMatrix();});resize.observe(host);
  function tick(now:number){const dt=Math.min(.05,(now-last)/1000||0);last=now;if(!paused)elapsed+=dt;controls.update();composer.update(paused?0:dt,elapsed,camera);renderer.render(composer.scene,camera);frameCount++;sampleTime+=dt;if(sampleTime>=1){const fps=Math.round(frameCount/sampleTime);$('metrics').textContent=`${fps} FPS · ${renderer.info.render.calls} draw calls · ${renderer.info.memory.geometries} geometries`;frameCount=0;sampleTime=0;}raf=requestAnimationFrame(tick);}
  renderLibrary();sync(false);focus(selected);if(restoreNotice)notice(restoreNotice);raf=requestAnimationFrame(tick);
  Object.defineProperty(window,'__UNIVERSE_ENVIRONMENTS__',{value:Object.freeze({snapshot:()=>({document:structuredClone(history.current),selected,quality:quality.value,paused,comparing,...composer.snapshot(),render:{calls:renderer.info.render.calls,triangles:renderer.info.render.triangles,...renderer.info.memory},catalog:{types:Object.keys(ENTITY_TYPES).length,surfaces:SURFACES.length,materials:MATERIALS.length,structures:STRUCTURES.length,phenomena:PHENOMENA.length,fx:FX_CATALOG.length,models:MODEL_NAMES.length}})})});
  window.addEventListener('pagehide',()=>{cancelAnimationFrame(raf);resize.disconnect();controls.dispose();transform.detach();transform.dispose();transform.removeFromParent();composer.dispose();renderer.dispose();},{once:true});
}
