import { ENTITY_TYPES,SCENE_FIELDS,type Field,type SceneDocument,type SceneEntity,type Value } from '../../world/generation/SceneDocument';

function element<K extends keyof HTMLElementTagNameMap>(tag:K,text?:string){const el=document.createElement(tag);if(text)el.textContent=text;return el;}
export function renderInspector(root:HTMLElement,scene:SceneDocument,entity:SceneEntity|undefined,onChange:(key:string,value:Value)=>void){
  const open=new Set(Array.from(root.querySelectorAll<HTMLDetailsElement>('details[open]')).map(d=>d.dataset.group));root.replaceChildren();
  root.append(element('small',entity?ENTITY_TYPES[entity.kind].name.toUpperCase():"WHOLE SCENE"),element('h2',entity?.name??"Environment and light"));
  const name=element('label',"Name"),nameInput=element('input');nameInput.value=entity?.name??scene.name;nameInput.maxLength=96;nameInput.id='entity-name';nameInput.onchange=()=>onChange('$name',nameInput.value);name.append(nameInput);root.append(name);
  if(entity){const visible=element('label',"Show object"),check=element('input');check.type='checkbox';check.checked=entity.visible;check.id='entity-visible';check.onchange=()=>onChange('$visible',check.checked);visible.className='check';visible.append(check);root.append(visible);
    const parentLabel=element('label',"Parent object"),parent=element('select');parent.id='entity-parent';const none=element('option',"Whole scene");none.value='';parent.append(none);for(const e of scene.entities)if(e.id!==entity.id){const option=element('option',e.name);option.value=e.id;parent.append(option);}parent.value=entity.parent??'';parent.onchange=()=>onChange('$parent',parent.value);parentLabel.append(parent);root.append(parentLabel);
    const transform=element('details');transform.open=open.has('transform');transform.dataset.group='transform';transform.append(element('summary',"Position, rotation and scale"));
    for(const [prop,title,min,max,step] of [['position',"Position",-1000000,1000000,10],['rotation',"Rotation, °",-360,360,1]] as const){const row=element('div');row.className='triple';row.append(element('span',title));for(let i=0;i<3;i++){const label=element('label',['X','Y','Z'][i]),input=element('input');input.type='number';input.id=`entity-${prop}-${i}`;input.value=String(entity[prop][i]);input.min=String(min);input.max=String(max);input.step=String(step);input.onchange=()=>onChange(`$${prop}.${i}`,Number(input.value));label.append(input);row.append(label);}transform.append(row);}
    const scale=element('label',"Uniform scale"),input=element('input');input.type='number';input.id='entity-scale';input.value=String(entity.scale);input.min='.01';input.max='100';input.step='.1';input.onchange=()=>onChange('$scale',Number(input.value));scale.append(input);transform.append(scale);root.append(transform);
  }
  const fields:Field[]=entity?ENTITY_TYPES[entity.kind].fields:SCENE_FIELDS,groups=new Map<string,HTMLDetailsElement>();
  const shortcuts=element('nav');shortcuts.className='inspector-shortcuts';root.insertBefore(shortcuts,root.querySelector('details'));
  for(const f of fields){let group=groups.get(f.group);if(!group){group=element('details');group.dataset.group=f.group;group.open=open.has(f.group)||groups.size===0;group.append(element('summary',f.group));groups.set(f.group,group);root.append(group);const jump=element('button',f.group);jump.onclick=()=>{const target=groups.get(f.group)!;target.open=true;target.scrollIntoView({block:'start',behavior:'smooth'});};shortcuts.append(jump);}
    const label=element('label',f.label);let control:HTMLInputElement|HTMLSelectElement;
    const value=(entity?.params??scene.settings)[f.key];
    if(f.type==='select'){const select=element('select');for(const o of f.options!){const option=element('option',o.label);option.value=String(o.value);select.append(option);}select.value=String(value);select.onchange=()=>{const option=f.options!.find(o=>String(o.value)===select.value)!;onChange(f.key,option.value);};control=select;}
    else {const input=element('input');input.type=f.type==='boolean'?'checkbox':f.type;input.value=typeof value==='number'?String(Math.round(value*10000)/10000):String(value);if(f.type==='number'){input.min=String(f.min);input.max=String(f.max);input.step=String(f.step);}if(f.type==='text')input.maxLength=96;if(f.type==='boolean'){input.checked=!!value;label.className='check';}input.onchange=()=>onChange(f.key,f.type==='number'?Number(input.value):f.type==='boolean'?input.checked:input.value);control=input;}
    if(entity?.params.texture&&['color0','color1','color2','geography','warp','geology','ocean','relief','circulation'].includes(f.key)){control.disabled=true;control.title="This setting applies to procedural surfaces. Set Surface map to Procedural surface.";}
    if(entity?.kind==='model'&&Number(entity.params.model)!==0&&f.group==="Engines"){control.disabled=true;control.title="Add a separate engine nozzle and parent it to this model.";}
    control.id=`field-${f.key}`;label.htmlFor=control.id;label.append(control);group.append(label);
  }
  if(entity&&(entity.kind==='planet'||entity.kind==='moon')){const note=element('p',entity.params.texture?"A baked map defines surface colours and patterns. Choose Procedural surface to edit them with parameters. Rings, clouds and moons are independent.":"All layers work together. You can also add separate moons or additional rings from the library.");note.className='help';root.append(note);}
}
